# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 17:13
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
                name='Claim',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('created', models.DateTimeField(auto_now_add=True)),
                    ('modified', models.DateTimeField(auto_now=True)),
                    ('date', models.DateTimeField()),
                    ('claim_value', models.FloatField()),
                    ('processed', models.BooleanField(db_index=True)),
                    ('authorising_manager',
                     models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='claim_authorising_manager', to=settings.AUTH_USER_MODEL,
                                       verbose_name='authorising manager')),
                    ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_owner',
                                                to=settings.AUTH_USER_MODEL, verbose_name='related owner')),
                    ('senior_manager',
                     models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='claim_senior_manager', to=settings.AUTH_USER_MODEL,
                                       verbose_name='senior manager')),
                ],
                options={
                    'abstract': False,
                },
        ),
        migrations.CreateModel(
                name='ClaimType',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('created', models.DateTimeField(auto_now_add=True)),
                    ('modified', models.DateTimeField(auto_now=True)),
                    ('name', models.CharField(max_length=100)),
                    ('count', models.BooleanField()),
                    ('allow_multiple', models.BooleanField(default=False)),
                ],
                options={
                    'abstract': False,
                },
        ),
        migrations.AddField(
                model_name='claim',
                name='type',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.ClaimType',
                                        verbose_name='related type'),
        ),
    ]
